"""AI Credit Analyst: explains scores, highlights risk and writes reports."""
from __future__ import annotations
from .llm_client import chat, is_llm_configured

SYSTEM = ("You are ScoreYedu's AI Credit Analyst for Zimbabwe's informal-sector "
          "borrowers. Write clearly, avoid jargon, be fair and responsible.")


def explain_score(applicant_name: str, score: int, breakdown: dict,
                  flags: list[str], features: dict) -> str:
    prompt = f"""Explain this Trust Score to a lender in 3 short paragraphs.
Name: {applicant_name}
Score: {score}/1000
Breakdown: {breakdown}
Risk flags: {flags}
Key facts: avg monthly inflow ${features['avg_monthly_inflow']}, income CV {features['income_cv']},
repayments made: {features['repayment_count']}, net ${features['net']}, months analysed: {features['months']}."""
    text = chat(prompt, SYSTEM)
    if text:
        return text
    # fallback explanation
    parts = ", ".join(f"{k.replace('_', ' ')}: {v}/250" for k, v in breakdown.items())
    risk = ("No major risk indicators were flagged." if not flags
            else "Risk indicators: " + "; ".join(flags) + ".")
    return (f"**{applicant_name}** scored **{score}/1000**. Component scores — {parts}.\n\n"
            f"Average monthly inflow is ${features['avg_monthly_inflow']} over {features['months']} months, "
            f"with income consistency CV of {features['income_cv']} and {features['repayment_count']} recorded repayments. "
            f"{risk}\n\n_Offline mode: set OPENAI_API_KEY for a richer LLM explanation._")


def credit_report(applicant_name: str, phone: str, features: dict, score: int,
                  breakdown: dict, flags: list[str], recommendation: dict) -> str:
    prompt = f"""Write a one-page credit assessment report in Markdown with sections:
Applicant Summary, Transaction Behaviour, Income Consistency, Cash Flow, Financial Discipline,
Repayment History, Risk & Fraud Indicators, Trust Score Breakdown, Recommendation.
Applicant: {applicant_name} ({phone}); Score {score}/1000; breakdown {breakdown};
flags: {flags}; recommendation: {recommendation}; features: {features}."""
    text = chat(prompt, SYSTEM)
    if text:
        return text
    lines = [
        f"# ScoreYedu Credit Assessment Report",
        f"**Applicant:** {applicant_name}  |  **Phone:** {phone}",
        f"**Trust Score:** {score}/1000",
        "",
        "## Trust Score Breakdown",
        *[f"- {k.replace('_', ' ').title()}: {v}/250" for k, v in breakdown.items()],
        "",
        "## Transaction Behaviour",
        f"- {features['tx_count']} transactions over {features['months']} months"
        f" (~{features['tx_per_month']}/month), {features['unique_counterparties']} unique counterparties",
        f"- Cash-out share of inflow: {features['cash_out_ratio']:.0%}, airtime share of spend: {features['airtime_ratio']:.0%}",
        "",
        "## Income Consistency",
        f"- Average monthly inflow: ${features['avg_monthly_inflow']}, regularity {features['regularity']:.0%}, CV {features['income_cv']}",
        "",
        "## Cash Flow",
        f"- Net position: ${features['net']}, positive months: {features['net_positive_months']}/{features['months']}, avg balance ${features['avg_balance']}",
        "",
        "## Financial Discipline",
        f"- Savings slope: ${features['savings_slope']}/month, late-night share {features['night_share']:.0%}",
        "",
        "## Repayment History",
        f"- {features['repayment_count']} repayments totalling ${features['repayment_total']}, regular: {features['repayment_regular']}",
        "",
        "## Risk & Fraud Indicators",
        *([f"- {f_}" for f_ in flags] if flags else ["- None flagged"]),
        "",
        "## Recommendation",
        f"**{recommendation['decision']}** — suggested loan ${recommendation['loan_amount']} "
        f"over {recommendation['repayment_weeks']} weeks. {recommendation['rationale']}",
        "",
        "_Generated by ScoreYedu (offline rule-based mode). Configure an LLM API key for narrative reports._",
    ]
    return "\n".join(lines)
